
spring:
  profiles:
#    active: profileNotLoaded   # NOT loaded!!??? .. cf bootstrap.yml
#    includes: activeprofile2  # NOT loaded ??

app:
  # used to import "classpath:foo-${app.env}.properties"
  env: test

  commonProp: application.yml-commonProp
  
  key1: application.yml-key1
  key2: application.yml-key2
  
  # default.. 
  app.bootstrap-prop1: DEFAULT application.yml-app.bootstrap-prop1
  bootprofile1-prop1: DEFAULT application.yml-app.bootprofile1-prop1  
  bootprofile2-prop1: DEFAULT application.yml-app.bootprofile2-prop1
  bootprofile3-prop1: DEFAULT application.yml-app.bootprofile3-prop1  
  bootprofile4-prop1: DEFAULT application.yml-app.bootprofile4-prop1
  